version: "3.5"
services:
  web:
    image: aishangwei/asw-js-web-demo:0.1
    ports:
      - 3000:3000
  db:
    image: aishangwei/asw-js-db-demo:0.1
    volumes:
      - js-demo-data:/var/lib/postgresql/data

volumes:
  js-demo-data:
